/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */
description = """
Week5 Practical on Gradle
Project name: ${project.name}
"""

plugins{
    //Apply the application plugin for building java application
    application
}

repositories{
    //Use Maven repository to get the libs
    mavenCentral()
}

dependencies{
    //Specify the TestNG framework
    testImplementation("org.testng:testng:7.4.0")

    // The dependency also uses the google guava library
    implementation("com.google.guava:guava:30.0-jre")
}

application{
    // Define the main class for the application.
    mainClass.set("GradleWeek5Practicals.app")
}

tasks.test{
    //use testNG for unit tests
    useTestNG()
}
