# The "Validate Gradle wrapper" step validates the checksums of Gradle Wrapper JAR files present in the source tree.
# And uploads the contents of that directory using the upload-artifact action.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

   steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'
  - name: Validate Gradle wrapper
    uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
  - name: Build with Gradle
    uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
    with:
      arguments: build
  - uses: actions/upload-artifact@v2
    with:
      name: Package
      path: build/libs
